### PR TITLE
Add zlib/1.2.12

### PR DESCRIPTION
**Pull request by uilianries**
Bump zlib to 1.2.12

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by uilianries** [comment]
This PR found a bug: https://github.com/conan-io/conan/issues/11045

**Comment by uilianries** [comment]
@czoido It seems link we are trying to use `Visual Studio` as compiler on the profile:

```
conan@C3I-PROD-WIN2 C:\J\w\NewToolchains_PR-15>conan create recipes/zlib/all/conanfile.py --name zlib --version 1.2.11 -pr:h=pr_host -pr:b=pr_host 
ERROR: Invalid setting 'Visual Studio' is not a valid 'settings.compiler' value.
Possible values are ['apple-clang', 'clang', 'gcc', 'intel-cc', 'mcst-lcc', 'msvc', 'qcc', 'sun-cc']
```

**Comment by czoido** [comment]
> @czoido It seems link we are trying to use `Visual Studio` as compiler on the profile:
> 
> ```
> conan@C3I-PROD-WIN2 C:\J\w\NewToolchains_PR-15>conan create recipes/zlib/all/conanfile.py --name zlib --version 1.2.11 -pr:h=pr_host -pr:b=pr_host 
> ERROR: Invalid setting 'Visual Studio' is not a valid 'settings.compiler' value.
> Possible values are ['apple-clang', 'clang', 'gcc', 'intel-cc', 'mcst-lcc', 'msvc', 'qcc', 'sun-cc']
> ```

@uilianries thanks for reporting, I'll fix the profiles in the ci and re-run the job

**Comment by uilianries** [comment]
Good to go!

**Review by czoido — APPROVED** [review]

**Pull request merged**
